import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';

const scene=new THREE.Scene();scene.background=new THREE.Color(0x182018);scene.fog=new THREE.Fog(0x182018,25,140);
const camera=new THREE.PerspectiveCamera(75,innerWidth/innerHeight,.05,300);const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;document.body.appendChild(renderer.domElement);
scene.add(new THREE.HemisphereLight(0xbfd8ff,0x39412d,1.5));const sun=new THREE.DirectionalLight(0xffffff,2);sun.position.set(20,35,10);sun.castShadow=true;scene.add(sun);
const player={pos:new THREE.Vector3(0,1.2,4),vel:new THREE.Vector3(),hp:100,stamina:100,weight:0,grounded:false,dead:false,climbing:false,carrying:null};
const keys={},mouse={left:false,right:false};const inventory=[null,null,null,null];let selected=0,chaos=0,weather='CLEAR',weatherTimer=8;const blocks=[],items=[],creatures=[],corpses=[],physics=[];
function box(name,x,y,z,sx,sy,sz,color=0x68705f,physical=false,mass=1){const m=new THREE.Mesh(new THREE.BoxGeometry(sx,sy,sz),new THREE.MeshStandardMaterial({color}));m.name=name;m.position.set(x,y,z);m.userData.size={x:sx,y:sy,z:sz};m.userData.mass=mass;m.userData.vel=new THREE.Vector3();m.castShadow=true;m.receiveShadow=true;scene.add(m);blocks.push(m);if(physical)physics.push(m);return m}
function sphere(x,y,z,r,color){const m=new THREE.Mesh(new THREE.SphereGeometry(r,12,8),new THREE.MeshStandardMaterial({color}));m.position.set(x,y,z);m.castShadow=true;scene.add(m);return m}
box('ground',0,-.3,-18,18,.6,90,0x3d4438);for(let i=0;i<18;i++){const z=-5-i*5,x=(Math.random()-.5)*3.5;box('platform',x,0,z,5+Math.random()*3,.8,4,0x5c6655);if(i%3===1)box('climbWall',x+(Math.random()>.5?2.7:-2.7),1.4,z,.7,2.8,4,0x4c5649)}box('finish',0,1,-105,10,2,2,0x8d6b35);
box('crate',-2,.55,-8,1.1,1.1,1.1,0x7a6040,true,8);box('crate',2,.55,-20,1.1,1.1,1.1,0x7a6040,true,8);box('rock',1,.35,-30,.7,.7,.7,0x555555,true,18);
function pickup(x,y,z,type='basic'){const m=new THREE.Mesh(new THREE.BoxGeometry(.45,.45,.45),new THREE.MeshStandardMaterial({color:type==='medkit'?0xe6e6e6:type==='ammo'?0x5d8bd3:0xd6a735}));m.position.set(x,y,z);m.userData={type};scene.add(m);items.push(m)}pickup(1,.5,1,'basic');pickup(-1,.5,-3,'medkit');pickup(0,.5,-12,'ammo');
const gun=new THREE.Mesh(new THREE.BoxGeometry(.18,.18,.65),new THREE.MeshStandardMaterial({color:0x222222}));gun.position.set(.32,-.25,-.6);camera.add(gun);scene.add(camera);
function spawnFlying(){const c=sphere((Math.random()-.5)*12,3+Math.random()*5,-20-Math.random()*70,.7,0x705050);c.userData={type:'flying',hp:3,baseY:c.position.y,vel:new THREE.Vector3(),mass:2};creatures.push(c)}function spawnClimber(){const c=sphere((Math.random()>.5?1:-1)*(3+Math.random()*3),.9,-25-Math.random()*60,.65,0x465f70);c.userData={type:'climber',hp:4,vel:new THREE.Vector3(),mass:3};creatures.push(c)}for(let i=0;i<3;i++)spawnFlying();for(let i=0;i<2;i++)spawnClimber();
function nearestItem(){let b=null,d0=2.5;for(const it of items){const d=it.position.distanceTo(player.pos);if(d<d0){b=it;d0=d}}return b}function updateSlots(){const r=document.querySelector('#slots');if(r)r.innerHTML=inventory.map((v,i)=>`<div class="slot ${i===selected?'selected':''}">${i+1}<br>${v||'—'}</div>`).join('')}function useSelected(){if(inventory[selected]==='medkit'){player.hp=Math.min(100,player.hp+35);inventory[selected]=null}else if(inventory[selected]==='ammo')inventory[selected]=null;updateSlots()}function interact(){const it=nearestItem();if(!it)return;inventory[selected]=it.userData.type;player.weight+=1;scene.remove(it);items.splice(items.indexOf(it),1);updateSlots()}
function nearCorpse(){let b=null,d0=2;for(const c of corpses){const d=c.position.distanceTo(player.pos);if(d<d0){b=c;d0=d}}return b}function toggleCarry(){if(player.carrying){player.carrying.userData.carrier=null;player.carrying=null;return}const c=nearCorpse();if(c){player.carrying=c;c.userData.carrier=player;c.userData.mass=70}}
function die(){if(player.dead)return;player.dead=true;player.hp=0;const c=box('corpse',player.pos.x,.65,player.pos.z,.8,1.3,.45,0x9b7770,true,70);c.userData.weight=1;corpses.push(c);document.querySelector('#message').textContent='ÖLDÜN — R ile yeni koşu'}function restart(){location.reload()}
addEventListener('keydown',e=>{keys[e.code]=true;if(e.code.startsWith('Digit')){selected=Math.min(3,Number(e.code.slice(-1))-1);updateSlots()}if(e.code==='KeyE'){if(nearestItem())interact();else if(nearCorpse()||player.carrying)toggleCarry();else useSelected()}if(e.code==='KeyR'&&player.dead)restart()});addEventListener('keyup',e=>keys[e.code]=false);addEventListener('mousedown',e=>{if(e.button===0){mouse.left=true;shoot()}if(e.button===2){mouse.right=true;document.body.requestPointerLock()}});addEventListener('mouseup',e=>{if(e.button===0)mouse.left=false;if(e.button===2)mouse.right=false});addEventListener('contextmenu',e=>e.preventDefault());addEventListener('mousemove',e=>{if(document.pointerLockElement===document.body){camera.rotation.y-=e.movementX*.002;camera.rotation.x-=e.movementY*.002;camera.rotation.x=Math.max(-1.45,Math.min(1.45,camera.rotation.x))}});
function shoot(){if(player.dead)return;const ray=new THREE.Raycaster();ray.setFromCamera(new THREE.Vector2(0,0),camera);const hits=ray.intersectObjects(creatures,false);if(hits.length&&hits[0].distance<35){const c=hits[0].object;c.userData.hp--;c.userData.vel.add(ray.ray.direction.clone().multiplyScalar(7/(c.userData.mass||1)));if(c.userData.hp<=0){scene.remove(c);creatures.splice(creatures.indexOf(c),1)}}for(const o of physics){const h=ray.intersectObject(o,false);if(h.length&&h[0].distance<15)o.userData.vel.add(ray.ray.direction.clone().multiplyScalar(10/(o.userData.mass||1)))}}
function tryClimb(dt){const f=new THREE.Vector3(0,0,-1).applyEuler(new THREE.Euler(camera.rotation.x,camera.rotation.y,0,'YXZ'));const hit=new THREE.Raycaster(camera.position,f.normalize(),0,1.5).intersectObjects(blocks,false).find(h=>h.object.name==='climbWall');if(mouse.right&&hit){player.climbing=true;player.vel.set(0,0,0);player.pos.y+=((keys.KeyW?1:0)-(keys.KeyS?1:0))*3.2*dt;player.pos.y=Math.min(5.5,player.pos.y);return true}player.climbing=false;return false}
function playerCollision(){player.grounded=false;for(const b of blocks){if(!['platform','climbWall','crate','rock'].includes(b.name))continue;const s=b.userData.size;const dx=player.pos.x-b.position.x,dz=player.pos.z-b.position.z;const top=b.position.y+s.y/2;if(Math.abs(dx)<s.x/2+.35&&Math.abs(dz)<s.z/2+.35&&player.pos.y>=top-.3&&player.pos.y<=top+1.3&&player.vel.y<=0){player.pos.y=top+1.2;player.vel.y=0;player.grounded=true}else if(Math.abs(dx)<s.x/2+.35&&Math.abs(dz)<s.z/2+.35&&player.pos.y<top+1.0){if(Math.abs(dx)>Math.abs(dz))player.pos.x=b.position.x+(dx>=0?s.x/2+.36:-s.x/2-.36);else player.pos.z=b.position.z+(dz>=0?s.z/2+.36:-s.z/2-.36);player.vel.x*=.25;player.vel.z*=.25}}}
function updatePhysics(dt){for(const o of physics){const v=o.userData.vel;o.userData.vel.multiplyScalar(Math.pow(.12,dt));o.userData.vel.y-=16*dt;o.position.addScaledVector(v,dt);const bottom=o.position.y-o.userData.size.y/2;if(bottom<0){o.position.y=o.userData.size.y/2;if(v.y<0)v.y*=-.2;v.x*=.72;v.z*=.72}}}
updateSlots();let last=performance.now();function tick(now){const dt=Math.min((now-last)/1000,.033);last=now;if(!player.dead){const dir=new THREE.Vector3((keys.KeyD?1:0)-(keys.KeyA?1:0),0,(keys.KeyS?1:0)-(keys.KeyW?1:0));if(dir.lengthSq())dir.normalize().applyAxisAngle(new THREE.Vector3(0,1,0),camera.rotation.y);const carrying=!!player.carrying;const sprint=(keys.ShiftLeft||keys.ShiftRight)&&player.stamina>1&&!player.climbing;const speed=(sprint?7:4)*(carrying?.7:1);player.vel.x=THREE.MathUtils.lerp(player.vel.x,dir.x*speed,.18);player.vel.z=THREE.MathUtils.lerp(player.vel.z,dir.z*speed,.18);if(sprint&&dir.lengthSq())player.stamina=Math.max(0,player.stamina-24*dt);else player.stamina=Math.min(100,player.stamina+38*dt);if(keys.Space&&player.grounded){player.vel.y=7;player.grounded=false}const climbing=tryClimb(dt);if(!climbing){player.vel.y-=18*dt;player.pos.addScaledVector(player.vel,dt)}else player.grounded=false;if(player.pos.y<1.2){player.pos.y=1.2;player.vel.y=0;player.grounded=true}playerCollision();updatePhysics(dt);if(player.carrying){player.carrying.position.copy(player.pos).add(new THREE.Vector3(0,.1,-.8));player.carrying.userData.vel.set(0,0,0)}camera.position.lerp(new THREE.Vector3(player.pos.x,player.pos.y+.45,player.pos.z),.5);
if(player.pos.z<-12){chaos=Math.min(100,chaos+dt*2);weatherTimer-=dt;if(weatherTimer<=0){weatherTimer=10+Math.random()*18;weather=Math.random()<.4?'ACID RAIN':Math.random()<.35?'STORM':'CLEAR';const w=document.querySelector('#weather');if(w)w.textContent=weather}if(weather==='ACID RAIN'&&Math.random()<dt*.8)player.hp=Math.max(0,player.hp-2);if(weather==='STORM'&&Math.random()<dt*.12)player.hp=Math.max(0,player.hp-12);if(Math.random()<dt*.035&&creatures.length<9)(Math.random()<.6?spawnFlying():spawnClimber())}
for(const c of creatures){if(c.userData.type==='flying'){c.position.y=c.userData.baseY+Math.sin(now*.002+c.position.x)*.8;c.position.x+=Math.sin(now*.001)*dt}const d=c.position.distanceTo(player.pos);if(d<1.3){const push=player.pos.clone().sub(c.position).normalize();player.vel.addScaledVector(push,1.5*dt);player.hp=Math.max(0,player.hp-(Math.random()<dt*.8?4:0))}}if(player.hp<=0)die();if(player.pos.z<-102){document.querySelector('#message').textContent='BİTİŞ! Koşuyu tamamladın — R ile yeniden';player.dead=true}}
document.querySelector('#hp').textContent=Math.round(player.hp);document.querySelector('#stamina').textContent=Math.round(player.stamina);document.querySelector('#weight').textContent=player.weight+(player.carrying?30:0);document.querySelector('#chaos').textContent=chaos<25?'LOW':chaos<60?'MEDIUM':'HIGH';const hb=document.querySelector('#hpbar'),sb=document.querySelector('#stambar');if(hb)hb.style.width=Math.max(0,player.hp)+'%';if(sb)sb.style.width=Math.max(0,player.stamina)+'%';renderer.render(scene,camera);requestAnimationFrame(tick)}addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});requestAnimationFrame(tick);